# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_auto_20170131_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettercategory',
            name='user',
        ),
        migrations.AlterField(
            model_name='letter',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category'),
        ),
        migrations.DeleteModel(
            name='LetterCategory',
        ),
    ]
