# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20170202_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name_plural': 'letters'},
        ),
        migrations.RenameField(
            model_name='letter',
            old_name='file_path',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
