# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20170208_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
