# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0008_auto_20170210_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
